//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARS_CPR_OUTSIDE_REP_TAB
    {
        public string OUTSIDE_REP { get; set; }
        public decimal REP_ID { get; set; }
    }
}
