//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionDataApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommissionEntities : DbContext
    {
        public CommissionEntities()
            : base("name=CommissionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER_INFO> CUSTOMER_INFO { get; set; }
        public virtual DbSet<CARS_CPR_COMMISSION_TAB> CARS_CPR_COMMISSION_TAB { get; set; }
        public virtual DbSet<CARS_CPR_OUTSIDE_REP_TAB> CARS_CPR_OUTSIDE_REP_TAB { get; set; }
    }
}
