//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommissionDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_INFO
    {
        public string CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string ASSOCIATION_NO { get; set; }
        public string PARTY { get; set; }
        public string DEFAULT_DOMAIN { get; set; }
        public string DEFAULT_LANGUAGE { get; set; }
        public string DEFAULT_LANGUAGE_DB { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTRY_DB { get; set; }
        public string PARTY_TYPE { get; set; }
        public string PARTY_TYPE_DB { get; set; }
        public string CORPORATE_FORM { get; set; }
        public string IDENTIFIER_REFERENCE { get; set; }
        public string IDENTIFIER_REF_VALIDATION { get; set; }
        public string IDENTIFIER_REF_VALIDATION_DB { get; set; }
        public string TEXT_ID_ { get; set; }
        public Nullable<decimal> PICTURE_ID { get; set; }
        public string OBJID { get; set; }
        public string OBJVERSION { get; set; }
        public string OBJKEY { get; set; }
    }
}
